---
bibliography: references.bib
---

# Deloppgave 4: Studiedesign

## Spørsmål/hypotese

Denne oppgaven sammenligner fem artikler som undersøker hvordan styrketrening og inntak av næring påvirker aktivering av signalproteiner, blant annet de tilhørende signalveien mTOR som kan relateres til translasjon av mRNA og proteinsyntese. @moore2011 ville undersøke mekanismer bak oppregulering av proteinsyntese som følge av styrketrening og proteininntak, og hadde en hypotese om at fosforylering av signalproteiner tilhørende mTOR vil øke i total mengde og varighet med å kombinere styrketrening og proteininntak, enn ved kun proteininntak. Det ble gjort et annet forsøk hvor de undersøkte om det ville være en dose-respons-effekt av hvor mye protein man inntar etter styrketreningen og mengden fosforylerte signalproteiner [@moore2009]. Hypotesen deres var at man ville se en sammenheng mellom dose-respons på proteininntak og fosforylerte signalproteiner. @farnfield2012 undersøkte om kombinasjonen av styrketrening og proteininntak hadde samme effekt på mTOR-signalveien hos gamle og unge. @figueiredo2019 undersøkte effekten av karbohydrater og styrketrening på signalproteinene, og hadde en hypotese om at inntak av karbohydrater ville gi større fosforylering av signalproteiner. I studien til @dreyer2008 undersøkte de hva som skjedde dersom man hadde inntak av både karbohydrater og proteiner etter styrketrening med en hypotese om at det ville gi større aktivering av mTOR enn å ikke innta noe næring etter trening.

## Logikk

Bakgrunnen for alle studiene er at styrketrening oppregulerer fosforylering av proteiner og enzymer i muskelcellen, som eksempel kinasene p70s6 og Akt, som tilhører en signalvei tilhørende et kompleks kalt mTOR. mTOR-komplekset er delaktige i regulering av translasjon av mRNA til muskelproteiner og er derfor med å regulerer proteinsyntesen. Tidligere forskning har også vist at inntak av essensielle aminosyrer kan øke aktiveringen av mTOR, uavhengig av styrketrening. Det gav grunnlag for forsøkene til @moore2011 og @farnfield2012. Større doser proteiner har vist å gi større respons i mTOR-signalveien i hvile, noe som @moore2009 vil undersøke om var samme tilfelle i etter å ha gjennomført styrketrening. For @farnfield2012 var det interressant å sammenligne effekten av proteininntak hos unge og gamle, da forskning har vist at muskulaturen hos eldre har en lavere respons på styrketrening enn hos unge.

Insulin skal også være en stimulator for aktivering av mTOR-komplekset og var grunnlag for hypotesene til @figueiredo2019 og @dreyer2008 om kombinasjon av karbohydrater og styrketrening vil gi større aktivering av mTOR. @figueiredo2019 undersøkte da effekten av kun karbohydrater, imens @dreyer2008 så på kombinasjonen av karbohydrater og proteiner.

## Metode

### Studiedesign

I forsøkene til @figueiredo2019, @farnfield2012 og @moore2011 ble studiet gjort within-subject hvor styrketreningen ble gjennomført på kun ett ben slik at personens andre ben ble sin egen kontroll. Forsøket til @figueiredo2019 var en tverrsnittstudie og deltakerne ble da undersøkt på ett tidspunkt, men forsøket ble repetert to ganger uten treningsintervensjon mellom. Deltakerne gjennomførte eksentrisk styrketrening på ett ben etterfulgt av inntak av enten karbohydrater eller placebo. Det ble tatt muskelbiopsi en og tre timer etter treningsøkten i begge ben. I studiet til @farnfield2012 ble det gjennomført som kontrollert studie hvor ble det gjennomført pre-tester med styrketrening på ett ben etterfulgt av inntak av proteiner. Det ble tatt muskelbiopsi i begge ben etter to timer. Deltakerne gjennomførte styrketrening på det ene benet i 12 uker. Avslutningvis gjorde de en post-test med samme protokoll som pre-test. Forsøket til @moore2011 ble gjort som tverrsnittsstudie hvor deltakerne gjorde en styrkeøkt på ett av benene, fikk proteintilskudd og gjorde flere biopsier på begge ben i timene etter økten. Også forsøket til @dreyer2008 var tverrsnittsstudie hvor det ble gjennomført styrketrening på begge ben og en time etterpå fikk noen av deltakerne tilskudd av karbohydrater og proteiner. Det ble tatt muskelbiopsi før, rett etter og de to neste timene etter styrkeøkten.

@moore2009 hadde et repeated-measurement design hvor de gjorde måling fem ganger med minimum en uke mellom hvert forsøk. Dette fordi forsøket fokuserte på akutt effekt og ikke langvarig effekt. Hvert forsøk var en styrkeøkt på begge ben og etterpå fikk de en drikke som inneholdt enten 0, 5, 10, 20 eller 40 gram eggeprotein. Det ble tatt muskelbiopsi en og fire timer etter styrketreningen og proteindrikken. Noen av variablene i studiene er randomisert. I @figueiredo2019 sin studie ble det randomisert om de skulle få karbohydrater eller placebo etter styrkeøkten, hos @farnfield2012 og @moore2011 var hvilket ben de skulle trene randomisert, hos @dreyer2008 om de fikk næring eller ikke etter styrketrening og hos @moore2009 om hvilken dose av protein de fikk etter trening. Studiet til @moore2009 er en crossover studie hvor hver forsøksperson fikk ulik behandling på hvert forsøk slik at effekten av ulik dose protein ikke er avhengig av forsøkspersonen som fikk den.

### Forsøkspersoner

Det er få deltakere i studiet til @figueiredo2019 (n = 10), @dreyer2008 (n = 16), @moore2011 (n = 7) og @moore2009 (n =6). @farnfield2012 sitt forsøk hadde størst utvalg med 31 deltakere. Med få deltakere er det mindre gunstig i forhold til statistiske utregninger, i tillegg til at det er lite grunnlag å estimere en effekt for en større populasjon ut fra så få personer. Ingen av studiene diskuterte eller forklarte størrelsen på forsøksgruppen.

Alle studiene ble gjort på friske menn med ulik fysisk bakgrunn. @moore2009 og @figueiredo2019 gjorde forsøk på unge menn som hadde minst to år erfaring med styrketrening, imens @dreyer2008, @farnfield2012 og @moore2011 undersøkte menn som ikke hadde trent strukturert styrketrening det siste året. Alle gruppene er representative for den allmenne befolkningen.

### Statistikk

Alle studiene brukte ANOVA for å se på endringen mellom gruppene eller benene som fikk ulik type behandling. @dreyer2008, @moore2011 og @farnfield2012 gjorde også t-test for å finne forskjellen mellom gruppene og for å finne endring for enkeltpersoner fra baseline til post. Alle studiene hadde satt signifikanse på p-verdi \< 0,05.

## Resultater

@figueiredo2019 fant en signifikant forskjell etter tre timer hvor de som hadde fått karbohydrater hadde mer fosforylert Akt enn gruppen uten inntak av karbohydrater, men det var ingen signifikant forskjell mellom gruppene på fosforylering av andre proteiner. @dreyer2008 sine resultater var at både gruppen med og uten inntak av proteiner og karbohydrater fikk en signifikant økning av fosforylert mTOR og p70s6k etter økten, og det var en signifikant forskjell mellom gruppene der næringsgruppen hadde størst økning. @farnfield2012 rapporterte fra den pre-testen en signifikant forskjell i den eldre gruppen hvor protein-gruppen hadde større fosforylering av p70s6k enn placebogruppen etter styrkeøkten. Fosforylering av mTOR var signifikant høyere i protein-gruppen hos både yngre og eldre. Det var ingen forskjell på fosforylering av Akt mellom protein- og placebogruppen hverken hos eldre eller yngre. På post-testen var det fortsatt ingen forskjell på Akt og nå heller ingen forskjell hos de eldre på fosforylering av p70s6k. Men kun den yngre gruppen hadde signifikant høyere fosforylering av mTOR på post-testen. @moore2011 fant ingen forskjell av fosforylering av mTOR mellom benet som trente og ikke. En til fem timer etter styrkeøkten og proteininntaket hadde det trente benet signifikant høyere fosforylering av p70s6k. Resultatet til @moore2009 var en signifikant økning av proteinsyntese ved inntak av 5, 10 og 20 gram proteiner, men etter det nådde hastigheten på proteinsyntesen ett platå. Det var ingen signifikant endring mellom dosene i fosforylering av p70s6k eller andre proteiner som ble undersøkt.

## Konklusjon

@figueiredo2019 hadde resultater som både støttet og motviste hypotesen sin, men konkluderte med at inntak av karbohydrater etter en styrkeøkt ikke hadde effekt på aktivering av mTOR. @dreyer2008 sin konklusjon var at inntak av både protein og karbohydrater etter styrketrening gir større aktivering av mTOR og derav øker proteinsyntesen ytterligere enn å ikke få noe næring etter treningen. Ut fra @farnfield2012 sin studie konkluderte de at i utrent tilstand vil kombinasjonen av styrketrening og proteininntak gi bl.a. større aktivering av mTOR og derav økt mRNA-translasjon hos både unge og gamle, men på trent muskel har ikke kosttilskudd ekstra effekt på eldre muskulatur. @moore2011 konkluderte fra sin studie at en kombinasjon av styrketrening og proteininntak ville gi en større aktivering av signalveien mTOR enn dersom man kun har et inntak av proteiner og ikke gjennomfører styrketrening. Forsøket til @moore2009 konkluderte med en dose-respons på proteininntaket etter styrketrening for proteindoser opp til 20 gram i sammenheng med hastigheten på proteinsyntese, men det hadde ingen tydelig sammenheng med fosforylering av signalproteiner tilhørende signalveien mTOR.
