---
bibliography: references.bib
---

# Deloppgave 3: Vitenskapsfilosofi

## Falsifikasjonisme

*Hva er Poppers falsifiserbarhetskriterium og hvilket spørsmål skal dette kriterium gi svar på? Hvorfor mener andre vitenskapsfilosofer (f.eks. Okasha) at vi ikke trenger å svare på dette spørsmålet? Hvem synes dere har rett?*

Falsifiserbarhetskriterium var en standard Karl Popper lagte for å kunne skille vitenskapelige teorier fra pseudovitenskapelige teorier. Kriteriet gikk ut på at for å være en vitenskapelig teori måtte teorien være falsifiserbar. For å kunne være en falsifiserbar teori måtte det kunne gå an å teste ut eller prøve å motbevise teorien. En falsifiserbar teori var f.eks. Einsteins teori på tidlig 1900-tallet om gravitasjon. Dette var en teori som var mulig å undersøke om ikke var sann. Andre forskere undersøkte teorien til Einstein med egne observasjoner og fikk resultater som bekreftet gravitasjonsteorien. Dersom det hadde blitt gjort observasjoner som viste at teorien ikke var sann, ville det si at teorien var falsifisert og kunne bli forkastet. I motsetning var det andre teorier som Freuds teori om psykoanalyse som Popper definerte som ikke falsifiserbar. Det var fordi denne teorien var for generell slik at den kunne brukes til å svare på alle spørsmål som kunne stilles til teorien og det var ingen måte å kunne bevise teorien feil. Når det dukket opp observasjoner som ikke stemte med teorien, kunne de komme med forklaringer i ettertid på hvorfor det likevel skulle stemme [@popper1985].  

Poppers falsifikasjonisme gidde et klart skille mellom vitenskap og pseudovitenskap. Andre vitenskapsfilosofer mente at vitenskapen ikke var så svart-hvitt i virkeligheten. Samir Okasha diskuterer blant annet videre på eksempelet om Einsteins gravitasjonsteori. To forskere skulle gjøre forsøk på gravitasjonsteorien og deres observasjoner stemte ikke med Einsteins teori. I følge falsifikasjonismen burde denne teorien skrotes da. Men forskerne holdt på teorien og prøvde å finne forklaring på hvorfor teorien ikke stemte med deres observasjoner. Det gjorde at de gjorde helt nye og betydningsfulle funn i tillegg til å bekrefte gravitasjonsteorien. Okasha forklarer at dette er et av flere eksempler i vitenskapen hvor forskere har gjort rett i å stå ved teorien selv om det blir gjort motsigende observasjoner. Dersom alle forskere hadde vraket teorien hver gang observasjoner ikke stemte overens ville prosessen i vitenskapen gått sakte fremover, mente Okasha [@okasha2016].

Selv om Poppers falsifiserbarhetskriterium eliminerer teorier som ikke er vitenskapelige, er det likevel som Okasha forklarer, flere gråsoner hvor det ikke er den beste fremgangsmåten. Selv tenker jeg at når en forsker har en teori, har forskeren kunnskap og andre observasjoner som grunnlag, noe som må bety at de fleste teorier ikke er helt på villspor. Og at dersom de da gjør empiriske funn som ikke stemmer med teorien så kan det likevel bety at forskeren er inne på noe. Jeg tenker også at dersom man gjør et funn som ikke støtter opp under teorien din så er det likevel ikke mislykket og bortkastet teori. Det kan heller gjøre at du noen ganger vil få et nytt perspektiv på teorien din. I mange tilfeller vil falsifikasjon eliminere teorier som ikke hører til vitenskap, men samtidig vil det være tilfeller hvor det ikke er relevant å falsifisere teorier, men å heller utforske videre.

## Hypotetisk-deduktiv metode og abduksjonisme

*Hva er strukturen på et bekreftende vitenskapelig argument ifølge den hypotetisk deduktive metode? Forklar ut fra Hempels artikkel, men bruk egne eksempel. Sammenlign også Hempels HD-metode med hvordan vitenskapelig bekreftelse fungerer ifølge enten abduksjon eller Bayesianisme.*

Med hypotetisk-deduktiv metode bekrefter man vitenskapelige argument ved å få positive resultater ut fra en deduksjon man gjør ut fra testene av en hypotese. Hempel forklarer hvordan første trinnet i strukturen i hypotetisk-deduktiv metode er å utvikle en teori eller en hypotese. Det neste trinnet i strukturen er å finne hvilke konsekvenser hypotesen gir eller består av. Det tredje trinnet i strukturen i
hypotetisk-deduktiv metode er å teste eller observere konsekvensene. I det fjerde trinnet ser man etter om konsekvensene bekrefter hypotesen eller ikke [@hempel1966]. Metoden bruker en deduktiv tilnærming med, da deduksjon er å trekke konklusjon ut fra premissene, dersom premissene er sanne er konklusjonen sann. Likevel mener Hempel at det blir brukt induksjon for å gjøre konklusjon. Det er med argumentet om at dersom man skal trekke konklusjon fra én test eller ett tilfelle og si at det samme utfallet vil skje i alle fremtidige tester, vil man da gjøre denne konklusjonen ut fra sannsynlighet eller sjanse, og det er da en induksjon og ikke deduksjon [@hempel1966].

Et eksempel på hvordan man kan bruke hypotetisk-deduktiv metode er på hypotesen «man får større muskler av å løfte tunge vekter». Trinn to blir å kartlegge konsekvensen, som er i denne hypotesen større muskler. I trinn tre ville man testet hypotesen med å løfte tunge vekter, som man i trinn fire ville brukt til å bekrefte teorien. Man har gjort deduksjon hvor premissene er at dersom hypotesen er sann vil tunge vekter gi deg større muskler og i testen fikk man større muskler, og konklusjonen er da at hypotesen er sann i dette tilfelle. Induktivt sier det at tunge vekter vil mest sannsynligvis gi deg større muskler.

En annen metode for å bekrefte vitenskapelige argumenter er abduksjon. Metoden er basert på at den
enkleste teorien er oftest den rette. Med abduksjon som metode har man flere teorier eller hypoteser som forklarer én eller flere konsekvenser. Den hypotesen som er mest simpel i tillegg til å forklare mest av konsekvensene er den riktige hypotesen. Den mest åpenbare forskjellen mellom hypotetisk-deduktiv metode og abduksjon er at hypotetisk-deduktiv metode er å argumentere for én hypotese, i motsetning til abduksjon hvor man argumenterer for og mot flere hypoteser.

Vi kan sammenligne abduksjon og hypotetisk-deduktiv metode om vektløfting. Dersom en person hadde observert at musklene hennes ble større, og hun har de siste ukene løftet tyngre vekter, kunne hun ut fra dette lagt en hypotese om at musklene hennes blir større av tyngre vekter ut fra hypotetisk-deduktiv metode. Dersom hun skulle brukt abduktiv argumentasjon, kunne hun komt med flere hypoteser som
f.eks. hun har fått større muskler fordi hun tenkte på tyngre vekter, eller at hun har fått større muskler fordi hun har fått en hormonsykdom. Den tredje hypotesen er den mest avanserte og ville bli vraket. Den andre hypotesen forklarer egentlig ikke konsekvensen og vil også bli forkastet. Da står den første
hypotesen om at tyngre vekter gir større muskler som den riktige hypotesen. Med abduktiv metode kan det føre til at man må se på konsekvensen fra ulike perspektiver som kan i noen tilfelle være en effektiv måte å sammenligne teorier istedenfor å utforske de én av gangen.

## Replikasjonskrisen

*Hva mener Alexander Bird er forklaringen til at mange resultat i noen vitenskaper ikke repliseres? Oppsummere Birds argument for dette. Sammenlign også Birds forklaring med noen av de andre forklaringene som Bird diskuterer i seksjon 4. Har Bird rett i at hans forklaring er bedre?*

I artikkelen til Alexander Bird blir vi introdusert for replikasjonskrisen som handler om at man at forskningen har frem til nå vært mangelfull og en konsekvens av dette er at man ikke får replisert tidligere forskning. For å illustrere alvorlighetsgraden av krisen hadde forskere prøvde å replisere 53 studier innenfor onkologi, hvor bare seks av disse kunne bli replisert på en aksepterbar måte [@bird2021]. Alexander Bird mener dette kommer av to grunner: svake hypoteser og ubetydelig signifikans. Den første grunnen kan forklares av basefrekvensfeilen som er at man kan få både falsk-positive og falsk-negative svar, som kan gjøre at det blir gjort feilslutning i forskning. Konklusjonen kan bli at en usann teori er sann, eller at en sann teori er usann. Det gjør at når en forsker repliserer en falsk-positiv teori vil den komme frem som usann i forsøket. Dette skjer når forskere overser forekomsten av usannheter. Angående signifikans i forskning forteller Bird at i fysikk har de større signifikans i forskningen. I forsøk på mennesker må hypotesen ha en signifikans på 95%, som vil se at 5% av resultatene kan være falsk-positiv. Dette forklarer Bird med et eksempel om at man kunne undersøke om mennesker er en terrorist eller ikke før de får gå om bord i et fly. Testen har en signifikans på 95% som vil si at dersom de hadde gjort testen på 100 personer som ikke er terrorister, vil likevel fem få et falsk-positivt resultat om at de er terrorist. Det mener Bird er et altfor høyt tall og burde ikke aksepteres i vitenskapelig forskning. I motsetning har forskning i fysikk en signifikans som tillater 0,00003% falsk-positive svar [@bird2021].

En annen forklaring på replikasjonskrisen kan være lav statistisk styrke. Han forklarer at dette er
størst problem i forskning på mennesker. Det er fordi på blant annet medisinske forsøk på mennesker er det ikke lett å gjøre tester på like mange mennesker som man kunne gjort på antall partikler i et forsøk i fysikk. Det gjør at forsøk med færre deltakere eller objekter vil ha lavere statistisk styrke. Desto flere deltakere man får med i et forsøk, desto mer styrke får forskningen. Dette er fordi å anta at effekten på en liten gruppe blir det samme som for resten av befolkningen er en større antagelse å ta enn dersom man hadde fått til å teste omtrent hele befolkningen og man må ta antagelse på at de få resterende vil få samme utfall. I eksempelvis fysikk er dette lettere å samle inn større mengder data og man får mer grunnlag til å trekke antagelser. Bird viser likevel frem utregningen som forklarer at selv med en høyere statistisk styrke i forskningen vil det likevel være en 31% sjanse for falsk-negativt svar [@bird2021]. Han mener at den statistiske styrken må opp, men at det likevel ikke er nok svar på replikasjonskrisen. I tillegg mener Bird det er en bias i forskning som kommer av at forskningen ikke alltid blir publisert når man får negativt utfall, altså ikke bekreftet hypotesen sin. Dersom det er gjort si fem like forsøk hvor fire mislykket og én gidde ønskelig resultat, og kun det bekreftende forsøket blir publisert, gir det feil inntrykk av repliserbarheten. Neste forsøk vil da tro at forsøket kan repliseres, men sjansen er heller størst for å ikke få til å replisere. I tillegg finnes det andre måter forskning manipulert, som med fjusk i datainnsamling, bearbeiding av data og hvordan resultatene blir fremstilt [@bird2021].

I konklusjon kan det virke som Birds argumenter om å minimere antall falske-positive eller falske-negative resultater er bra for å styrke påliteligheten til forskning. Selv synes jeg også at argumentet om lav statistisk styrke kan ha mye å si hvis det blir sett i sammenheng med forskning i fysikk.
